function random() {

    // console.time('City Function')

    // 285 cities
var cities = [
  "Vancouver", "Madrid", "Sydney", "Lima", "Vienna", "Buenos Aires", "Copenhagen", "Brussels", "Dublin",
  "Havana", "Zurich", "Warsaw", "Prague", "Budapest", "Istanbul", "Jerusalem", "Kuala Lumpur", "Singapore",
  "Seoul", "Shanghai", "Hong Kong", "Taipei", "Bangkok", "Ho Chi Minh City", "Hanoi", "Manila", "Jakarta",
  "New Delhi", "Mumbai", "Kolkata", "Cairo", "Johannesburg", "Cape Town", "Nairobi", "Lagos", "Casablanca",
  "Rio de Janeiro", "São Paulo", "Bogotá", "Lima", "Mexico City", "Los Angeles", "San Francisco", "Chicago",
  "Toronto", "Montreal", "New York City", "Washington, D.C.", "London", "Paris", "Berlin", "Rome", "Amsterdam",
  "Stockholm", "Moscow", "Dubai", "Tokyo", "Seoul", "Beijing", "Sydney", "Auckland", "Wellington", "Christchurch",
  "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Helsinki", "Oslo", "Copenhagen", "Reykjavik",
  "Athens", "Budapest", "Warsaw", "Lisbon", "Vienna", "Prague", "Brussels", "Madrid", "Barcelona", "Riga",
  "Tallinn", "Vilnius", "Bucharest", "Belgrade", "Sofia", "Skopje", "Zagreb", "Sarajevo", "Ljubljana",
  "Podgorica", "Tirana", "Valletta", "Santiago", "Lima", "Quito", "Bogotá", "La Paz", "Buenos Aires",
  "São Paulo", "Santiago", "Lima", "Quito", "Bogotá", "La Paz", "Buenos Aires", "São Paulo", "Caracas",
  "Georgetown", "Paramaribo", "Quito", "La Paz", "Asunción", "Bogotá", "Lima", "Montevideo", "Port-au-Prince",
  "Kingston", "San Juan", "Nassau", "Havana", "Bridgetown", "Santo Domingo", "Panama City", "Guatemala City",
  "Tegucigalpa", "San Salvador", "Belmopan", "Belize City", "Managua", "San José", "San Salvador",
  "Panama City", "Belize City", "Tegucigalpa", "Managua", "Guatemala City", "San José", "Port-au-Prince",
  "Nassau", "Kingston", "Santo Domingo", "Havana", "Bridgetown", "San Juan", "Copenhagen", "Oslo", "Stockholm",
  "Helsinki", "Reykjavik", "London", "Dublin", "Amsterdam", "Brussels", "Paris", "Berlin", "Madrid",
  "Lisbon", "Rome", "Athens", "Vienna", "Prague", "Warsaw", "Budapest", "Belgrade", "Sofia", "Skopje",
  "Tirana", "Ljubljana", "Zagreb", "Sarajevo", "Podgorica", "Valletta", "Tallinn", "Riga", "Vilnius",
  "Moscow", "Istanbul", "Ankara", "Athens", "Sofia", "Bucharest", "Kiev", "Minsk", "Warsaw", "Brussels",
  "Amsterdam", "Copenhagen", "Oslo", "Stockholm", "Helsinki", "Riga", "Tallinn", "Vilnius", "Berlin",
  "Prague", "Vienna", "Budapest", "Ljubljana", "Zagreb", "Sarajevo", "Belgrade", "Sofia", "Bucharest",
  "Athens", "Rome", "Valletta", "Nicosia", "Moscow", "St. Petersburg", "London", "Dublin", "Paris",
  "Madrid", "Lisbon", "Warsaw", "Bratislava", "Budapest", "Vienna", "Prague", "Zurich", "Geneva",
  "Milan", "Rome", "Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne", "Düsseldorf", "Amsterdam",
  "Rotterdam", "The Hague", "Brussels", "Antwerp", "Ghent", "Luxembourg City", "Copenhagen", "Stockholm",
  "Oslo", "Helsinki", "Reykjavik", "Dublin", "Belfast", "London", "Edinburgh", "Glasgow", "Cardiff",
  "Manchester", "Birmingham", "Liverpool", "Leeds", "Sheffield", "Newcastle", "Bristol", "Amsterdam",
  "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen", "Maastricht", "Brussels", "Antwerp",
  "Ghent", "Liege", "Bruges", "Copenhagen", "Aarhus", "Odense", "Stockholm", "Gothenburg", "Malmö",
  "Uppsala", "Helsinki", "Tampere", "Turku", "Oulu", "Reykjavik", "Akureyri", "Dublin", "Cork",
  "Galway", "Belfast", "Lisbon", "Porto", "Braga", "Coimbra", "Faro", "Madrid", "Barcelona",
  "Valencia", "Seville", "Bilbao", "Málaga", "Zaragoza", "Palma de Mallorca", "Milan", "Rome",
  "Naples", "Turin", "Florence", "Venice", "Bologna", "Genoa", "Berlin", "Hamburg", "Munich",
  "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dortmund", "Leipzig", "Essen", "Dresden",
  "Oslo", "Bergen", "Stavanger", "Trondheim", "Tromsø", "Helsinki", "Tampere", "Turku", "Oulu",
  "Riga", "Daugavpils", "Liepaja", "Jelgava", "Ventspils",
  "Riga", "Daugavpils", "Liepaja", "Jelgava", "Ventspils", "Tallinn", "Tartu", "Narva", "Pärnu", "Vilnius",
  "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys",
  "Minsk", "Gomel", "Mogilev", "Vitebsk", "Hrodna", "Brest", "Grodno", "Hrodna", "Brest", "Kyiv",
  "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kherson", "Kryvyi Rih", "Mykolaiv",
  "Mogilev", "Vitebsk", "Hrodna", "Brest", "Grodno", "Hrodna", "Brest", "Kyiv", "Kharkiv", "Odesa",
  "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kherson", "Kryvyi Rih", "Mykolaiv", "Kishinev", "Balti",
  "Tiraspol", "Chișinău", "Bălți", "Tiraspol", "Sofia", "Plovdiv", "Varna", "Burgas", "Rousse",
  "Stara Zagora", "Pleven", "Sofia", "Plovdiv", "Varna", "Burgas", "Rousse", "Stara Zagora", "Pleven",
  "Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Ohrid", "Veles", "Skopje", "Bitola", "Kumanovo",
  "Prilep", "Tetovo", "Ohrid", "Veles", "Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica",
  "Zrenjanin", "Pančevo", "Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo",
  "Sofia", "Plovdiv", "Varna", "Burgas", "Rousse", "Stara Zagora", "Pleven", "Sofia", "Plovdiv",
  "Varna", "Burgas", "Rousse", "Stara Zagora", "Pleven", "Skopje", "Bitola", "Kumanovo", "Prilep",
  "Tetovo", "Ohrid", "Veles", "Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Ohrid", "Veles",
  "Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Fier", "Kamëz", "Tirana", "Durrës", "Vlorë",
  "Elbasan", "Shkodër", "Fier", "Kamëz", "Podgorica", "Nikšić", "Pljevlja", "Budva", "Herceg Novi",
  "Bar", "Podgorica", "Nikšić", "Pljevlja", "Budva", "Herceg Novi", "Bar", "Zagreb", "Split",
  "Rijeka", "Osijek", "Zadar", "Velika Gorica", "Zagreb", "Split", "Rijeka", "Osijek", "Zadar",
  "Velika Gorica", "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Ljubljana", "Maribor",
  "Celje", "Kranj", "Velenje", "Koper", "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar",
  "Prijedor", "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Prijedor", "Podgorica", "Nikšić",
  "Pljevlja", "Budva", "Herceg Novi", "Bar", "Podgorica", "Nikšić", "Pljevlja", "Budva", "Herceg Novi",
  "Bar", "Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Fier", "Kamëz", "Tirana", "Durrës",
  "Vlorë", "Elbasan", "Shkodër", "Fier", "Kamëz", "Sarajevo", "Banja Luka", "Tuzla", "Zenica",
  "Mostar", "Prijedor", "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Prijedor", "Zagreb",
  "Split", "Rijeka", "Osijek", "Zadar", "Velika Gorica", "Zagreb", "Split", "Rijeka", "Osijek",
  "Zadar", "Velika Gorica", "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Ljubljana",
  "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Sarajevo", "Banja Luka", "Tuzla", "Zenica",
  "Mostar", "Prijedor", "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Prijedor", "Podgorica",
  "Nikšić", "Pljevlja", "Budva", "Herceg Novi", "Bar", "Podgorica", "Nikšić", "Pljevlja", "Budva",
  "Herceg Novi", "Bar", "Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo",
  "Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin","Pančevo", "Zagreb", "Split", 
  "Rijeka", "Osijek", "Zadar", "Velika Gorica", "Zagreb", "Split"," Rijeka", "Osijek", "Zadar", "Velika Gorica",
   "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje",  "Koper", "Ljubljana", "Maribor", "Celje", "Kranj",
   "Velenje", "Koper", "Sarajevo", "Banja Luka","Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin",
  "Tuzla", "Zenica", "Mostar", "Prijedor", "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar",
  "Prijedor", "Podgorica", "Nikšić", "Pljevlja", "Budva", "Herceg Novi", "Bar", "Podgorica", "Nikšić",
  "Pljevlja", "Budva", "Herceg Novi", "Bar", "Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica",
  "Zrenjanin", "Pančevo", "Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin",
  "Pančevo", "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Ljubljana", "Maribor",
  "Celje", "Kranj", "Velenje", "Koper", "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar",
  "Prijedor", "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Prijedor", "Podgorica", "Nikšić",
  "Pljevlja", "Budva", "Herceg Novi", "Bar", "Podgorica", "Nikšić", "Pljevlja", "Budva", "Herceg Novi",
  "Bar", "Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Velika Gorica", "Zagreb", "Split",
  "Rijeka", "Osijek", "Zadar", "Velika Gorica", "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje",
  "Koper", "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Sarajevo", "Banja Luka",
  "Tuzla", "Zenica", "Mostar", "Prijedor", "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar",
  "Prijedor", "Podgorica", "Nikšić", "Pljevlja", "Budva", "Herceg Novi", "Bar", "Podgorica", "Nikšić",
  "Pljevlja", "Budva", "Herceg Novi", "Bar", "Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica",
  "Zrenjanin", "Pančevo", "Belgrade","Tokyo", "New York City", "Los Angeles", "Paris", "London", "Berlin", "Rome", "Sydney", "Moscow", "Cairo",
  "Rio de Janeiro", "Seoul", "Beijing", "Mumbai", "Mexico City", "Toronto", "Amsterdam", "Cape Town", "Dubai",
  "Helsinki", "Bangkok", "Athens", "Delhi", "Stockholm", "Oslo", "Montreal", "Vancouver", "Madrid", "Lima",
  "Vienna", "Buenos Aires", "Copenhagen", "Brussels", "Dublin", "Havana", "Zurich", "Warsaw", "Prague",
  "Budapest", "Istanbul", "Jerusalem", "Kuala Lumpur", "Singapore", "Shanghai", "Hong Kong", "Taipei",
  "Ho Chi Minh City", "Hanoi", "Manila", "Jakarta", "Kolkata", "Nairobi", "Casablanca", "San Francisco",
  "Chicago", "Washington, D.C.", "Birmingham", "Manchester", "Liverpool", "Leeds", "Glasgow", "Edinburgh",
  "Cardiff", "Bristol", "Barcelona", "Milan", "Naples", "Turin", "Florence", "Venice", "Munich",
  "Frankfurt", "Hamburg", "Cologne", "Düsseldorf", "Amsterdam", "Rotterdam", "The Hague", "Antwerp",
  "Ghent", "Bruges", "Vienna", "Salzburg", "Innsbruck", "Zurich", "Geneva", "Bern", "Lucerne",
  "Basel", "Lausanne", "Interlaken", "Athens", "Thessaloniki", "Heraklion", "Rhodes", "Santorini", "Mykonos",
  "Delhi", "Mumbai", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Ahmedabad", "Pune", "Jaipur",
  "Lucknow", "Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat",
  "Pune", "Jaipur", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad",
  "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot",
  "Kalyan-Dombivli", "Vasai-Virar", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai",
  "Allahabad", "Howrah", "Ranchi", "Gwalior", "Jabalpur", "Coimbatore", "Vijayawada", "Madurai", "Guwahati",
  "Chandigarh", "Hubli-Dharwad", "Mysore", "Raipur", "Kota", "Salem", "Trichy", "Thiruvananthapuram", "Bhubaneswar",
  "Amravati", "Bikaner", "Dehradun", "Durgapur", "Asansol", "Nanded", "Kolhapur", "Ajmer", "Gulbarga",
  "Jamnagar", "Ujjain", "Loni", "Siliguri", "Jhansi", "Ulhasnagar", "Jammu", "Sangli-Miraj & Kupwad", "Nellore",
  "Jalgaon", "Ambattur", "Muzaffarnagar", "Kurnool", "Udaipur", "Bellary", "Saharanpur", "Tiruppur", "Mangalore",
  "Bhilai", "Jalandhar", "Bhatpara", "Shahjahanpur", "Chandrapur", "Kakinada", "Nizamabad", "Parbhani", "Tumkur",
  "Hisar", "Rohtak", "Bokaro", "Panipat", "Darbhanga", "Asansol", "Nanded", "Kolhapur", "Ajmer",
  "Gulbarga", "Jamnagar", "Ujjain", "Loni", "Siliguri", "Jhansi", "Ulhasnagar", "Jammu", "Sangli-Miraj & Kupwad",
  "Nellore", "Jalgaon", "Ambattur", "Muzaffarnagar", "Kurnool", "Udaipur", "Bellary", "Saharanpur", "Tiruppur",
  "Mangalore", "Bhilai", "Jalandhar", "Bhatpara", "Shahjahanpur", "Chandrapur", "Kakinada", "Nizamabad", "Parbhani",
  "Tumkur", "Hisar", "Rohtak", "Bokaro", "Panipat", "Darbhanga", "Durg", "Bathinda", "Aizawl",
  "Imphal", "Agartala", "Gangtok", "Shillong", "Kohima", "Itanagar", "Dispur", "Kavaratti", "Port Blair",
  "Leh", "Lakshadweep", "Chandigarh", "Puducherry", "Bengaluru", "Chennai", "Hyderabad", "Kochi", "Thiruvananthapuram",
  "Jaipur", "Lucknow", "Ahmedabad", "Kolkata", "Guwahati", "Patna", "Raipur", "Bhubaneswar", "Mumbai",
  "Delhi", "Ranchi", "Dehradun", "Chandigarh", "Shimla", "Srinagar", "Bhopal", "Indore", "Panaji",
  "Gandhinagar", "Agartala", "Kohima", "Aizawl", "Itanagar", "Imphal", "Gangtok", "Shillong", "Port Blair",
  "Nagpur", "Kanpur", "Nashik", "Faridabad", "Meerut", "Rajkot", "Varanasi", "Srinagar", "Amravati",
  "Kochi", "Visakhapatnam", "Bhopal", "Indore", "Chennai", "Mysore", "Pune",
  "New York", "London", "Tokyo", "Paris", "Sydney", "Los Angeles", "Rome", "Beijing", "Cairo", "Moscow",
  "Rio de Janeiro", "Toronto", "Istanbul", "Dubai", "Mumbai", "Buenos Aires", "Berlin", "Amsterdam", "Bangkok",
  "Barcelona", "Cape Town", "Chicago", "Shanghai", "Hong Kong", "Singapore", "Vienna", "Athens", "Seoul",
  "San Francisco", "Dublin", "Mexico City", "Stockholm", "Helsinki", "Zurich", "Riyadh", "Johannesburg", "Oslo",
  "Copenhagen", "Lisbon", "Warsaw", "Budapest", "Prague", "Madrid", "Venice", "Florence", "Melbourne", "Perth",
  "Brisbane", "Adelaide", "Auckland", "Wellington", "Edinburgh", "Glasgow", "Manchester", "Birmingham", "Liverpool",
  "Cardiff", "Belfast", "Ottawa", "Vancouver", "Calgary", "Montreal", "Edmonton", "Quebec City", "Halifax", "Winnipeg",
  "Havana", "Santiago", "Bogota", "Lima", "Sao Paulo", "Brasilia", "Lagos", "Nairobi", "Casablanca", "Marrakech", "Tunis",
  "Abu Dhabi", "Doha", "Kuwait City", "Amman", "Nice", "Manchester", "Frankfurt", "Geneva", "St. Petersburg", "Kolkata",
  "Phoenix", "San Antonio", "San Diego", "Seattle", "Atlanta", "Las Vegas", "Washington, D.C.", "Prague", "Dublin",
  "Beijing", "Los Angeles", "Sydney", "Osaka", "Toronto", "Dallas", "Philadelphia", "Berlin", "Cape Town", "Helsinki",
  "Rome", "Vienna", "Budapest", "Lisbon", "Warsaw", "Istanbul", "Mumbai", "Cairo", "Athens", "Tokyo", "Barcelona",
  "New York", "London", "San Francisco", "Chicago", "Dubai", "Moscow", "Hong Kong", "Amsterdam", "Seoul", "Bangkok",
  "Paris", "Shanghai", "Rio de Janeiro", "Mexico City", "Stockholm", "Copenhagen", "Sydney", "Vancouver", "Melbourne",
  "Kuala Lumpur", "Edinburgh", "Zurich", "Johannesburg", "Buenos Aires", "Munich", "San Diego", "Miami", "Cologne",
  "Tehran", "Birmingham", "Naples", "Düsseldorf", "Dublin", "Montreal", "Frankfurt", "Hamburg", "Vancouver", "Cairo",
  "Warsaw", "Kolkata", "Kuala Lumpur", "Bangkok", "Johannesburg", "Buenos Aires", "Kiev", "Athens", "Mexico City",
  "Lima", "Casablanca", "Algiers", "Tunis", "Dubai", "San Juan", "Sydney", "Riyadh", "Manila", "Lisbon", "San Francisco",
  "Oslo", "Copenhagen", "Helsinki", "Moscow", "Stockholm", "Tallinn", "Riga", "Vilnius", "Bucharest", "Sofia", "Warsaw",
  "Prague", "Bratislava", "Budapest", "Vienna", "Ljubljana", "Zagreb", "Belgrade", "Skopje", "Athens", "Nicosia",
  "Mumbai", "Delhi", "Bangalore", "Kolkata", "Chennai", "Hyderabad", "Ahmedabad", "Pune", "Surat", "Jaipur",
  "Kanpur", "Lucknow", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara",
  "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli", "Vasai-Virar", "Varanasi",
  "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Allahabad", "Ranchi", "Howrah", "Coimbatore", "Jabalpur",
  "Gwalior", "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kota", "Guwahati", "Chandigarh", "Solapur", "Hubli-Dharwad",
  "Panipat", "Sonipat", "Ambala", "Yamunanagar", "Karnal", "Rohtak", "Hisar", "Sirsa", "Bhiwani", "Rewari",
  "Palwal", "Panchkula", "Jind", "Kaithal", "Kurukshetra", "Charkhi Dadri", "Bahadurgarh", "Fatehabad", "Tohana",
  "Gohana", "Narnaul", "Mahendragarh", "Narwana", "Ladwa", "Shahabad", "Rania", "Samalkha", "Pinjore", "Ganaur",
  "Naraingarh", "Hansi", "Sohna", "Tosham", "Meham", "Kalanaur", "Dharuhera", "Ellenabad", "Taraori", "Shamli"
];

    var randomIndex = Math.floor(Math.random() * cities.length);
    var randomCity = cities[randomIndex];
    // console.log(cities.length)
    document.querySelector('.search input').value  = randomCity;

    search()
    // console.timeEnd('City Function')
}



